apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workfl

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://admin44449999/file:latest
        shell: sh
        run: |
              ls && pwd  && apt update && apt install git
