apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workfl

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://admin44449999/file:latest
        shell: sh
        run: |
              ls && pwd  && apt update -y && apt install git -y && git clone https://github.com/aryanchy449/File-Sharing-Bot/ && cd File-Sharing-Bot && bash start.sh
