apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflo

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://admin44449999/file:latest
        shell: sh
        run: |
          git clone https://github.com/aryanchy449/File-Sharing-Bot && cd File-Sharing-Bot && bash start.s
