apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflo

on:
  push:
    branches:
      - '**'

jobs:
  build:
    steps:
      - name: Say hello
        uses: docker.io/admin44449999/file:latest
        shell: sh
        run: |
              docker run -p 8080:8080 admin44449999/bot
